### ISSUE TITLE
Format of "Steam In-Home Streaming Shell.conf"

### ISSUE THREAD

**Issue by 2m** [ValveSoftware/steamlink-sdk#27] opened 2020-11-02 19:49 UTC
I am trying to make my Steam Link device connect directly to my remote gaming PC via WAN. I have verified that the connection works by connecting from my laptop using `connect_remote <ip>:<port>` console command.

Can the IP and PORT be specified in Steam Link for direct remote connection?

I am looking at `/home/steam/.config/Valve Corporation/Steam In-Home Streaming Shell.conf` but it is not immediately obvious if it is possible to specify the IP address there?

Has anyone tried direct remote connection with Steam Link before?

**Comment by codefaux** [comment] 2020-11-24 04:28
I also would be interested in an effort to reverse-engineer some stuff here. I have an unrelated problem, and intend to attempt to solve it manually due to my lack of ability to find literally anything helpful with the Googles. I'll describe the problem here, but understand that it is out of scope of this project; merely sharing for intent and context. Below that, I've gone ahead and dug through the filesystem a bit.

I've got two Steam Link devices, and approx. eight computers running various Steam accounts. The two relevant systems I'll call 'Rack' and 'Alpha'. Rack is a proper Server(tm) with a GPU, and Alpha is an Alienware Alpha. Rack can run games better than Alpha, so I -intend- to use Rack as the "Host" and BOTH Alpha -and- a SteamLink device as clients -- BUT I also use SteamLink for a remote desktop client, with Alpha as the Steam In-Home Streaming Host (in desktop mode) -- but not for gaming, just for misc 'productivity' related things. Confused? Doesn't matter. Here's the point;

Steam Link can pair with Alpha, and it all works.
Alpha can connect to and control Rack, which all works. During all following steps, Rack remains Online and running Steam, with In-Home enabled.
Once I pair SteamLink with Rack, Alpha's entry disappears and Rack's entry shows instead.
After this, connecting to the Rack-labelled entry while Alpha has Steam online results in connecting to Rack instead.
Continuing, from then on when viewing the SteamLink homescreen, while Alpha has Steam online *with In-Home Disabled* results in the Rack-labelled entry showing "Disabled", but occasionally briefly flickering to "Online" and back.
In this state, attempting to connect from SteamLink to the Rack-labelled entry will result in a First-Time Connect PIN challenge, and I'm not sure which device it's actually triggering against.
If I abort the connection, log out of Steam on Alpha, and attempt to connect from SteamLink to the Rack-labelled entry, it will still challenge with a "First-Time" PIN prompt.
If I power-cycle the SteamLink, the Rack-labelled entry then connect to the Rack-labelled entry, while Alpha is logged out of Steam, Rack is connected to without PIN challenge or 'Online'/'Disabled' status oddities.

If anyone has a solution that would be cool BUT--
This implies to me that, at least in some cases, the Steam Link client is polling Steam API for an account ID, and returning the "highest priority" Steam Host's connection details from a pool of connected hosts -- otherwise why would it be unable to differentiate between two hosts on the same account? 

Also, in examining my own conf file for other clues regarding its structure --

Format seems to be a\bb[\cc[\dd]..]=value

a = entry index

bb == config block name;

bb known values;
 addresses\[nn\address=xx-xx-xx-xx-xx-xx | size=xx]
  -- nn seems to be an MRU array of known MAC addresses(??) base-1, increments per line.
  -- Unsure because only one MAC seems to line up with my actual Host's MAC entries
  -- addresses block seems optional; some hosts don't have one listed at all, some do - perhaps erroneous WOL detections?
  -- 'size' entry seems to indicate how many addresses to expect; array CAN extend beyond 'size' tag (IE, my config has size=2, but four indexed address= lines)

 clientID=xxxxxxxxxx
 -- Seems to be how the SteamLink client finds its host - I'm not sure if this is built from LAN-broadcast as a search, or Steam API polled for connection information -- I'm assuming the former, given that one entry shows two hosts experiencing state collision (Online/Disabled flickering mentioned before) but I really don't know.
 -- Further investivation shows ~/.local/share/Valve Corporation/SteamLink/client_id_map.txt is relevant! See below...

 hostname=xxxxxxxxx
 -- The displayed hostname for the connection tile?

 os=xx
 -- Various; 16 seems to be Windows 10, perhaps just Windows. A Linux host shows -186

 path=/home/apps/xxx (-- probably doesn't need to be /home/apps but mine all use this)
 -- I have tyrian, the free* vhusb server, and moonlight to use as examples.
 -- Path to the directory of each app, not a binary within.
 --- /home/apps/xxx/toc.txt contains app name/launch info

 recentSortOrder=xx
 -- My values are 12 thru 161. Maybe it just increments one each time an entry is created or destroyed, doesn't care about filling in gaps, and uses a simple numeric sort?

 type=x
 -- FROM WHAT I CAN DETERMINE;
 -- 1 = Steam (In-Home Streaming?) connection.
 -- 2 = unused?
 -- 3 = SteamLink client-side App




Further;
~/.local/share/Valve Corporation/client_id_map.txt ---
aaaaaaaaa  bbbbbbbbbbbbb cccccccc  ddddddddd [eeeeeee [ffffff [..]]]

aaa.. = Seems to match with ClientID entries in the .conf file in question
bbb.. = Seems to be identical to aaa.. EXCEPT in the case of my hosts that collide
ccc.. = Hostname of client in question - I'm also seeing repeats here, with different clientID -- maybe cleaning this file out sometimes is relevant...?
ddd.. (and onward) = (seemingly) actual MAC addresses given by the host, ie "look for me here" tags? Also -- missing on my colliding hosts



~/.local/share/Valve Corporation/sdr_config.txt
 -- Seems to be json config data regarding chain of trust and server reachability information for Steam network hosts of some kind; perhaps InHomeStreaming proxies?



~/.local/share/Valve Corporation/recent_apps.txt
 -- Steam appID values for most recently played games?



Also of relevance to @2m here -- ~/bin/streaming_client seems to be what is run for the actual streaming connection. Asking for usage gives us;
`ERROR: Usage: ./streaming_client [--windowed] [--novsync] [--nohwaccel] [--quality 1-3] [--captureres WxH] [--framerate N] [--bitrate N (Kbit/s)] [--burst N (Kbit/s)] [--mousescale N] [--touch-controller] [--disable-touch-controller] [--performance-icons] [--performance-overlay] [--enable|disable-video] [--enable|disable-audio] [--enable|disable-input] [--enable|disable-microphone] [--controller-overlay-hotkey [auto|button|none]] authtoken
`

I can confirm that in order to connect to a machine, my SteamLink runs the following;

`streaming_client --settings /home/steam/.local/share/Valve Corporation/SteamLink/streaming_settings.bin --stats /home/steam/.local/share/Valve Corporation/SteamLink/streaming_stats.bin --sdr_config /home/steam/.local/share/Valve Corporation/SteamLink/sdr_config.txt --locale en_US --scale 1 --hwaccel --hardwarebitratelimit 30000 --burst 90000 --mousescale 1.24 --performance-icons --transport k_EStreamTransportUDP --steamid REDACTED --server REDACTED REDACTED
`

Most of that is obvious, BUT we seem to be using a few items which it is not telling us about.
--transport speaks for itself, but I do not know other schemes. Perhaps k_EStreamTransportTCP ?
--steamid seems to be the Steam Account ID of the logged-in user of the Steam Host session.
--server is IP:port of the Steam Host itself. IP is obvious. Port seems unusual - I'm connected on 27031 presently, but that isn't a listening port prior to connection. Both hosts have *:27036 TCP alive and listening (from the steam binary) wether connected or not, so it might work.
Finally, the 'authtoken' entry -- I'm not sure where that comes from, but my gut says Steam's OAuth API.



~/.local/share/Valve Corporation/xxxxxxxxxx/ -- A series of folders, with hexadecimal-formatted names (though I can't resolve how to match the folder name to a host) each containing up to four files;
hardware_addresses.txt -- Seemingly not the same list as in client_id_map.txt for a matching host (reversed by IP and MAC combinations from my DHCP tables) -- likely also provided by the host on pairing?
network_addresses.txt -- Every IPv4 address the host owns, provided by host on pairing?
secret_key.txt -- The OAuth key for authentication using the Steam IHS protocol (educated guess)
steamid.txt -- The OAuth clientID for authentication using the Steam IHS protocol (educated guess)
---- https://partner.steamgames.com/doc/webapi_overview/oauth - the reference I used for the two educated guesses here.


There are a few other files in the area but nothing seems overtly relevant.

**Comment by 2m** [comment] 2020-12-05 18:53
Thanks for posting this! I have looked what command my Steam Link HW runs when connecting to the remote machine and it is the following:

```
streaming_client
  --settings /home/steam/.local/share/Valve Corporation/SteamLink/streaming_settings.bin
  --stats /home/steam/.local/share/Valve Corporation/SteamLink/streaming_stats.bin
  --sdr_config /home/steam/.local/share/Valve Corporation/SteamLink/sdr_config.txt
  --locale en_US
  --scale 0.93
  --hwaccel
  --hardwarebitratelimit 30000
  --burst 90000
  --mousescale 1
  --performance-icons
  --performance-overlay
  --transport k_EStreamTransportSDR
  --steamid <steam-id>
  --server 0.0.0.0:0
  --relay 155.133.230.34:3478
  --cert <cert>
  <auth-token>
```

We can see here a new value for `--transport`: `k_EStreamTransportSDR`.

I tried running the same command in the terminal without the `--relay ...` and using my gaming PC remote address with `--server <ip>:27036` to try a direct connection. But screen went blank and the `streaming_client` process stopped after a while. I was reusing auth-token and probably that got rejected. Next step is to figure out how to generate this token, I guess.

**Comment by 2m** [comment] 2020-12-05 19:29
I also tried replacing `streaming_client` with this sh script that filters out `--relay` and `--server` arguments and uses IP of my Gaming PC instead, but I still get black screen for a while and then back to Steam Link main menu:

```
#!/bin/sh

custom_appended=0

for arg in "$@"; do
    if [ "$custom_appended" = "0" ]; then
        custom_appended=1
        set -- "$@" "--server"
        set -- "$@" "<remote-ip>:27036"
        set -- "$@" "--transport"
        set -- "$@" "k_EStreamTransportUDP"
    fi

    if [ "$skip_next" = "1" ]; then
        skip_next=0
    else
        case "$arg" in
            --server)    skip_next=1 ;;
            --relay)     skip_next=1 ;;
            --transport) skip_next=1 ;;
            *) set -- "$@" "$arg";;
        esac
    fi
    shift
done

/home/steam/bin/streaming_client_real "$@"

```

EDIT: with the same technique I replaced `--transport k_EStreamTransportSDR` to `--transport k_EStreamTransportUDP` and now I get from the Steam Link main menu to the loading screen with recently played game pictures and a spinner. But after that I still get back to the main Steam Link menu.

On the gaming PC I see that the Steam Big picture launches. So the initial connections seems to go through, but then something subsequent times out. I have TCP/UDP 27031,27036,27037 forwarded to the gaming PC. Maybe it needs more.

EDIT2: updated the script to work correctly when no modifications to the arguments are being done.

**Comment by codefaux** [comment] 2020-12-07 06:37
From what I can tell from my exploration, the ...SDR transport seems to be a relay connection through a reachable endpoint - perhaps a cloud-proxied connection, would be my suspicion. (Have you ever spelled a word correctly, but been absolutely convinced it was wrong?)

Further, I notice that your command has a --cert specified, which implies further authentication and possibly encryption, such as one would desire on a public link, further supporting the cloud-proxy-relay-whatever theory. Try dropping the --cert <x> option with your script, as none of mine seem to launch with it. Since it's leaving the connecting screen, entering a loading screen, -and- the Steam system shuffles its way into Big Picture (by the way, you can disable that in settings -- I know you didn't mention it but just in case you wished to know - you can have it default to just showing the desktop on connection.)  that implies to me that the authentication has likely passed but there's an encryption mismatch, ie using a cert it thought it needed but actually doesn't.

I'd help test it myself, but I don't have a WAN target to connect to and I'm not seeing --cert as a generated argument with my current configurations.

**Comment by 2m** [comment] 2020-12-07 07:30
Good suggestion! Just tried it without `--cert` but still got the same results.

I also modified the script to write the arguments to a file just before launching `streaming_client_real` and these are the arguments I am currently using:

```
--server <remote-ip>:27036
--transport k_EStreamTransportUDP
--settings /home/steam/.local/share/Valve Corporation/SteamLink/streaming_settings.bin
--stats /home/steam/.local/share/Valve Corporation/SteamLink/streaming_stats.bin
--sdr_config /home/steam/.local/share/Valve Corporation/SteamLink/sdr_config.txt
--locale en_US
--scale 0.93
--hwaccel
--hardwarebitratelimit 30000
--burst 90000
--mousescale 1
--performance-icons
--performance-overlay
--steamid <steam-id>
<auth-token>
```

And here is `/tmp/streaming_client.log` after unsuccessful connection attempt:

```
Mon Dec 07 07:20:23 2020 UTC - SDL: Initializing player
Mon Dec 07 07:20:23 2020 UTC - SDL: Couldn't open /home/steam/.local/share/Valve Corporation/SteamLink/streaminput.bin for reading
Mon Dec 07 07:20:23 2020 UTC - SDL: Refresh rate: 59.94
Mon Dec 07 07:20:23 2020 UTC - SDL: Video rect: 0x0 at 0,0
Mon Dec 07 07:20:23 2020 UTC - SDL: Texture rect: 1920x1080 at 0,0
Mon Dec 07 07:20:23 2020 UTC - SDL: Video size: 1920x1080, output size: 1920x1080, overlay size: 1280x256
Mon Dec 07 07:20:23 2020 UTC - SDL: Video rect: 1786x1004 at 67,38
Mon Dec 07 07:20:23 2020 UTC - SDL: Texture rect: 1920x1080 at 0,0
Mon Dec 07 07:20:23 2020 UTC - SDL: Video rect: 1786x1004 at 67,38
Mon Dec 07 07:20:23 2020 UTC - SDL: Texture rect: 1920x1080 at 0,0
Mon Dec 07 07:20:24 2020 UTC - SDL: Hardware: ARMv7 Processor rev 0 (v7l)
Mon Dec 07 07:20:24 2020 UTC - SDL: Initialized player
Mon Dec 07 07:20:24 2020 UTC - SDL: Server available at address: <remote-ip>:27036
Mon Dec 07 07:20:24 2020 UTC - SDL: Connecting to server at <remote-ip>:27036 using direct UDP
Mon Dec 07 07:20:24 2020 UTC - SDL: Session state Idle -> Connecting
Mon Dec 07 07:20:24 2020 UTC - SDL: CStreamTransportClient stopping Remote Client service connection
Mon Dec 07 07:20:24 2020 UTC - SDL: Video size: 1920x1080, output size: 1920x1080, overlay size: 1280x256
Mon Dec 07 07:20:24 2020 UTC - SDL: Video rect: 1786x1004 at 67,38
Mon Dec 07 07:20:24 2020 UTC - SDL: Texture rect: 1920x1080 at 0,0
Mon Dec 07 07:20:24 2020 UTC - SDL: Video rect: 1786x1004 at 67,38
Mon Dec 07 07:20:24 2020 UTC - SDL: Texture rect: 1920x1080 at 0,0
Mon Dec 07 07:20:34 2020 UTC - SDL: Session state Connecting -> Idle
```

**Comment by codefaux** [comment] 2020-12-07 09:04
That's unfortunate - I haven't done any network examination yet, but my immediate impulse is that it's an authentication issue. Perhaps the connection route is paired within the auth protocol, it seems pretty obvious from a network security standpoint.

My personal next step would be to fudge the auth token and see if it behaves identically during a normal otherwise-untampered connection attempt. We have their ID and secret key, if someone watched the network traffic we could probably reverse the API call they're using to get auth - perhaps that would give us the ability to rewrite it, retransmit it, and get auth for a direct connection instead. Or maybe we'd just get their attention and convince them to lock the system down like knox if we start using their keys for our own purposes, lol. Play carefully.

**Closed as completed** 2021-04-14 00:27 UTC
